services:
  db:
    image: postgres:16-alpine
    container_name: eventostech-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 325158
      POSTGRES_DB: eventostech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # interface pra ver o banco sem instalar nada (PgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: eventostech-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: